name: Component tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Start server
        run: yarn preview

      - name: Poczekaj na uruchomienie serwera
        run: npx wait-on http://localhost:5173 --timeout 120000

      - name: Run test
        timeout-minutes: 1
        run: yarn test:cypress
